# Generated by Django 3.0.7 on 2020-07-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserConversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserQuestion', models.CharField(max_length=2000)),
                ('ChatbotResponse', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Webdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=2000)),
            ],
        ),
    ]
